CREATE TABLE public.encounter_vitals (
  vital_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id bigint NOT NULL REFERENCES public.encounters(encounter_id) ON DELETE CASCADE,
  patient_id bigint NOT NULL REFERENCES public.patients(patient_id) ON DELETE RESTRICT,
  recorded_by_staff_id bigint NOT NULL REFERENCES public.careplus_staff_users(id) ON DELETE RESTRICT,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  systolic_bp smallint, diastolic_bp smallint, pulse_rate smallint,
  temperature_c numeric(4,1), respiratory_rate smallint, spo2_percent numeric(5,2),
  weight_kg numeric(6,2), height_cm numeric(6,2), bmi numeric(5,2), pain_score smallint, notes text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT encounter_vitals_bp_check CHECK ((systolic_bp IS NULL OR systolic_bp BETWEEN 40 AND 300) AND (diastolic_bp IS NULL OR diastolic_bp BETWEEN 20 AND 200)),
  CONSTRAINT encounter_vitals_pulse_check CHECK (pulse_rate IS NULL OR pulse_rate BETWEEN 20 AND 250),
  CONSTRAINT encounter_vitals_temp_check CHECK (temperature_c IS NULL OR temperature_c BETWEEN 25 AND 45),
  CONSTRAINT encounter_vitals_resp_check CHECK (respiratory_rate IS NULL OR respiratory_rate BETWEEN 5 AND 80),
  CONSTRAINT encounter_vitals_spo2_check CHECK (spo2_percent IS NULL OR spo2_percent BETWEEN 0 AND 100),
  CONSTRAINT encounter_vitals_weight_check CHECK (weight_kg IS NULL OR weight_kg BETWEEN 0 AND 500),
  CONSTRAINT encounter_vitals_height_check CHECK (height_cm IS NULL OR height_cm BETWEEN 30 AND 250),
  CONSTRAINT encounter_vitals_bmi_check CHECK (bmi IS NULL OR bmi BETWEEN 1 AND 100),
  CONSTRAINT encounter_vitals_pain_check CHECK (pain_score IS NULL OR pain_score BETWEEN 0 AND 10)
);
CREATE INDEX encounter_vitals_encounter_idx ON public.encounter_vitals(encounter_id, recorded_at DESC);
CREATE INDEX encounter_vitals_patient_idx ON public.encounter_vitals(patient_id, recorded_at DESC);
CREATE TRIGGER encounter_vitals_set_updated_at BEFORE UPDATE ON public.encounter_vitals FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.encounter_diagnoses (
  encounter_diagnosis_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id bigint NOT NULL REFERENCES public.encounters(encounter_id) ON DELETE CASCADE,
  patient_id bigint NOT NULL REFERENCES public.patients(patient_id) ON DELETE RESTRICT,
  condition_id bigint NULL REFERENCES public.conditions(condition_id) ON DELETE RESTRICT,
  diagnosis_text text NOT NULL,
  severity public.severity_level, is_primary boolean NOT NULL DEFAULT false, notes text,
  diagnosed_by_doctor_id bigint NOT NULL REFERENCES public.doctors(doctor_id) ON DELETE RESTRICT,
  diagnosed_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT encounter_diagnoses_text_nonempty CHECK (length(btrim(diagnosis_text)) > 0)
);
CREATE INDEX encounter_diagnoses_encounter_idx ON public.encounter_diagnoses(encounter_id);
CREATE INDEX encounter_diagnoses_patient_idx ON public.encounter_diagnoses(patient_id, diagnosed_at DESC);
CREATE INDEX encounter_diagnoses_condition_idx ON public.encounter_diagnoses(condition_id);
CREATE TRIGGER encounter_diagnoses_set_updated_at BEFORE UPDATE ON public.encounter_diagnoses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.patient_allergies (
  allergy_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES public.patients(patient_id) ON DELETE CASCADE,
  allergen text NOT NULL, allergy_type text, reaction text, severity public.severity_level,
  status text NOT NULL DEFAULT 'Active', onset_date date, notes text,
  recorded_by_staff_id bigint NOT NULL REFERENCES public.careplus_staff_users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT patient_allergies_allergen_nonempty CHECK (length(btrim(allergen)) > 0),
  CONSTRAINT patient_allergies_status_check CHECK (status IN ('Active','Inactive'))
);
CREATE INDEX patient_allergies_patient_idx ON public.patient_allergies(patient_id, status);
CREATE INDEX patient_allergies_allergen_idx ON public.patient_allergies(lower(allergen));
CREATE TRIGGER patient_allergies_set_updated_at BEFORE UPDATE ON public.patient_allergies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.encounter_vitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encounter_diagnoses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_allergies ENABLE ROW LEVEL SECURITY;

CREATE POLICY encounter_vitals_admin_all ON public.encounter_vitals FOR ALL TO authenticated USING (public.has_careplus_role('admin'::public.careplus_staff_role)) WITH CHECK (public.has_careplus_role('admin'::public.careplus_staff_role));
CREATE POLICY encounter_vitals_doctor_own ON public.encounter_vitals FOR ALL TO authenticated USING (public.has_careplus_role('doctor'::public.careplus_staff_role) AND EXISTS (SELECT 1 FROM public.encounters e WHERE e.encounter_id = encounter_vitals.encounter_id AND e.doctor_id = public.current_careplus_doctor_id())) WITH CHECK (public.has_careplus_role('doctor'::public.careplus_staff_role) AND EXISTS (SELECT 1 FROM public.encounters e WHERE e.encounter_id = encounter_vitals.encounter_id AND e.doctor_id = public.current_careplus_doctor_id() AND e.patient_id = encounter_vitals.patient_id));
CREATE POLICY encounter_diagnoses_admin_all ON public.encounter_diagnoses FOR ALL TO authenticated USING (public.has_careplus_role('admin'::public.careplus_staff_role)) WITH CHECK (public.has_careplus_role('admin'::public.careplus_staff_role));
CREATE POLICY encounter_diagnoses_doctor_own ON public.encounter_diagnoses FOR ALL TO authenticated USING (public.has_careplus_role('doctor'::public.careplus_staff_role) AND diagnosed_by_doctor_id = public.current_careplus_doctor_id() AND EXISTS (SELECT 1 FROM public.encounters e WHERE e.encounter_id = encounter_diagnoses.encounter_id AND e.doctor_id = public.current_careplus_doctor_id())) WITH CHECK (public.has_careplus_role('doctor'::public.careplus_staff_role) AND diagnosed_by_doctor_id = public.current_careplus_doctor_id() AND EXISTS (SELECT 1 FROM public.encounters e WHERE e.encounter_id = encounter_diagnoses.encounter_id AND e.doctor_id = public.current_careplus_doctor_id() AND e.patient_id = encounter_diagnoses.patient_id));
CREATE POLICY patient_allergies_admin_all ON public.patient_allergies FOR ALL TO authenticated USING (public.has_careplus_role('admin'::public.careplus_staff_role)) WITH CHECK (public.has_careplus_role('admin'::public.careplus_staff_role));
CREATE POLICY patient_allergies_doctor_own_patients ON public.patient_allergies FOR ALL TO authenticated USING (public.has_careplus_role('doctor'::public.careplus_staff_role) AND EXISTS (SELECT 1 FROM public.encounters e WHERE e.patient_id = patient_allergies.patient_id AND e.doctor_id = public.current_careplus_doctor_id())) WITH CHECK (public.has_careplus_role('doctor'::public.careplus_staff_role) AND EXISTS (SELECT 1 FROM public.encounters e WHERE e.patient_id = patient_allergies.patient_id AND e.doctor_id = public.current_careplus_doctor_id()));
CREATE POLICY encounter_vitals_service_role_all ON public.encounter_vitals FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY encounter_diagnoses_service_role_all ON public.encounter_diagnoses FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY patient_allergies_service_role_all ON public.patient_allergies FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.validate_clinical_record_patient_match()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $$
DECLARE encounter_patient bigint;
BEGIN
  SELECT patient_id INTO encounter_patient FROM public.encounters WHERE encounter_id = NEW.encounter_id;
  IF encounter_patient IS NULL OR encounter_patient <> NEW.patient_id THEN RAISE EXCEPTION 'Clinical record patient does not match encounter patient'; END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.validate_clinical_record_patient_match() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_clinical_record_patient_match() TO service_role;
CREATE TRIGGER encounter_vitals_patient_match BEFORE INSERT OR UPDATE ON public.encounter_vitals FOR EACH ROW EXECUTE FUNCTION public.validate_clinical_record_patient_match();
CREATE TRIGGER encounter_diagnoses_patient_match BEFORE INSERT OR UPDATE ON public.encounter_diagnoses FOR EACH ROW EXECUTE FUNCTION public.validate_clinical_record_patient_match();