-- CarePlus Phase 1: clinical encounter foundation.
CREATE TYPE public.encounter_status AS ENUM ('Draft','In Progress','Completed','Signed','Cancelled');

CREATE TABLE public.encounters (
  encounter_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id bigint NULL REFERENCES public.appointments(appointment_id) ON DELETE SET NULL,
  patient_id bigint NOT NULL REFERENCES public.patients(patient_id) ON DELETE RESTRICT,
  doctor_id bigint NOT NULL REFERENCES public.doctors(doctor_id) ON DELETE RESTRICT,
  branch_id bigint NOT NULL REFERENCES public.branches(branch_id) ON DELETE RESTRICT,
  encounter_type public.appointment_type NOT NULL DEFAULT 'Consultation',
  status public.encounter_status NOT NULL DEFAULT 'Draft',
  chief_complaint text,
  clinical_summary text,
  assessment text,
  plan text,
  started_at timestamptz,
  completed_at timestamptz,
  signed_at timestamptz,
  signed_by_doctor_id bigint REFERENCES public.doctors(doctor_id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT encounters_completed_after_started CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at),
  CONSTRAINT encounters_signed_requires_completed CHECK (signed_at IS NULL OR status = 'Signed'),
  CONSTRAINT encounters_signed_by_required CHECK (signed_at IS NULL OR signed_by_doctor_id IS NOT NULL)
);

CREATE UNIQUE INDEX encounters_appointment_unique ON public.encounters(appointment_id) WHERE appointment_id IS NOT NULL;
CREATE INDEX encounters_patient_id_idx ON public.encounters(patient_id);
CREATE INDEX encounters_doctor_id_idx ON public.encounters(doctor_id);
CREATE INDEX encounters_branch_id_idx ON public.encounters(branch_id);
CREATE INDEX encounters_status_idx ON public.encounters(status);
CREATE INDEX encounters_created_at_idx ON public.encounters(created_at DESC);

CREATE TRIGGER encounters_set_updated_at
BEFORE UPDATE ON public.encounters
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.encounters ENABLE ROW LEVEL SECURITY;

CREATE POLICY encounters_admin_all ON public.encounters
FOR ALL TO authenticated
USING (public.has_careplus_role('admin'::public.careplus_staff_role))
WITH CHECK (public.has_careplus_role('admin'::public.careplus_staff_role));

CREATE POLICY encounters_doctor_select_own ON public.encounters
FOR SELECT TO authenticated
USING (public.has_careplus_role('doctor'::public.careplus_staff_role) AND doctor_id = public.current_careplus_doctor_id());

CREATE POLICY encounters_doctor_insert_own ON public.encounters
FOR INSERT TO authenticated
WITH CHECK (public.has_careplus_role('doctor'::public.careplus_staff_role) AND doctor_id = public.current_careplus_doctor_id());

CREATE POLICY encounters_doctor_update_own ON public.encounters
FOR UPDATE TO authenticated
USING (public.has_careplus_role('doctor'::public.careplus_staff_role) AND doctor_id = public.current_careplus_doctor_id())
WITH CHECK (public.has_careplus_role('doctor'::public.careplus_staff_role) AND doctor_id = public.current_careplus_doctor_id());

CREATE POLICY encounters_service_role_all ON public.encounters
FOR ALL TO service_role
USING (true) WITH CHECK (true);